### ISSUE TITLE
Getting error after successfully logging in

### ISSUE THREAD

**Issue by TonyGregg** [onelogin/onelogin-oidc-java#4]
After successfully verifying the user name / password & the control comes back to call back - localhost:8081/login, I see an 401 error from localhost:8081/login

Why? I just followed the code and instructions as given.

**Comment by bvaisakh** [comment]
Same issue happens for me as well.

**Comment by dyrczyk** [comment]
Duplicate of https://github.com/onelogin/onelogin-oidc-java/issues/14
